version: '3.4'

services:
  secilstore.web:
    image: ${DOCKER_REGISTRY-}secilstoreweb
    build:
      context: .
      dockerfile: src/SecilStore.Web/Dockerfile
    ports:
    - "8080:8080" 
    - "8081:8081" 

  service-a:
    image: ${DOCKER_REGISTRY-}servicea
    build:
      context: .
      dockerfile: src/Service-A/Dockerfile
    ports:
    - "8082:8082"
    - "8083:8083"


  service-b:
    image: ${DOCKER_REGISTRY-}serviceb
    build:
      context: .
      dockerfile: src/Service-B/Dockerfile
    ports:
    - "8084:8084"
    - "8085:8085"

