version: '3.4'

services:
  secilstore.web:
    image: ${DOCKER_REGISTRY-}secilstoreweb
    build:
      context: .
      dockerfile: src/SecilStore.Web/Dockerfile
    ports:
    - "8080:80" 
    - "8081:443" 

  service-a:
    image: ${DOCKER_REGISTRY-}servicea
    build:
      context: .
      dockerfile: src/Service-A/Dockerfile
    ports:
    - "8082:80"
    - "8083:443"


  service-b:
    image: ${DOCKER_REGISTRY-}serviceb
    build:
      context: .
      dockerfile: src/Service-B/Dockerfile
    ports:
    - "8084:80"
    - "8085:443"

